### ISSUE TITLE
Deprecated by xlinkHref in react@0.14

### ISSUE THREAD

**Issue by thom4parisot** [Ahrengot/react-svg-use#3]
Hey,

just a heads up to notify you `xlink:href` is actually supported by React as of `xlinkHref` attribute.
You can find it in the list here: https://facebook.github.io/react/docs/tags-and-attributes.html#svg-attributes

I spotted that in this comment: https://github.com/facebook/react/issues/1657#issuecomment-197052674

Cheers :-)

**Comment by p2227** [comment]
I use it for some legacy React 0.13 projects.

**Comment by Ahrengot** [comment]
@oncletom yup, just updated the readme the other day. Thanks for the heads-up though :)
